### ISSUE TITLE
Just a question: using a bed file as input, what are the rules used to map genes from the genomic coordinates ?

### ISSUE THREAD

**Issue by veroniquevoisin** [MaayanLab/enrichr_issues#17] opened 2021-04-23 02:30 UTC
is it the nearest gene or is there a rule like find nearest gene with a maximum distance of +-10kb, etc...
Thanks!!

**Comment by maxim-k** [comment] 2021-06-03 14:34
Closed as a duplicate of #9

**Closed as completed by maxim-k** 2021-06-03 14:34 UTC
